"""Typed infrastructure contracts; pure domain does not import implementations."""
from typing import Protocol, TypeVar
from datetime import datetime
from uuid import UUID
from tsr.contracts import ActorContext, ClaimedJob, EncryptedBlob, Result, WorkRef, RecoveryReport
T = TypeVar('T')

class CryptoPort(Protocol):
    def encrypt(self,data:bytes)->EncryptedBlob: ...
    def decrypt(self,blob:EncryptedBlob)->bytes: ...

class FileStore(Protocol):
    def delete_blob(self,ref:str)->Result[bool]:
        """Success confirms absence; bool distinguishes removal from already absent."""
        ...

class Repository(Protocol[T]):
    def get(self,id:UUID)->T|None: ...
    def get_owned(self,ctx:ActorContext,id:UUID,lock:bool=False)->Result[T]: ...
    def insert(self,dto:T)->T: ...
    def save(self,dto:T)->T: ...
    def list_by_case(self,case_id:UUID)->tuple[T,...]: ...
    def list_by_owner(self,owner_id:UUID)->tuple[T,...]: ...

class WorkRepository(Protocol):
    def enqueue_unique(self,work:WorkRef)->WorkRef: ...
    def claim_next(self,kind:str,worker_id:str,now:datetime,lease_seconds:int,bot_scope:str|None=None)->ClaimedJob|None: ...
    def renew_lease(self,claim:ClaimedJob,now:datetime,lease_seconds:int)->bool: ...
    def finish_if_claim(self,claim:ClaimedJob,now:datetime,status:str='succeeded')->bool: ...
    def recover_expired(self,now:datetime,max_attempts:int=5,bot_scope:str|None=None)->RecoveryReport: ...

class Clock(Protocol):
    def now(self)->datetime: ...

class IdGenerator(Protocol):
    def new_id(self)->UUID: ...
